[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "neurigui"
version = "2.81.0"
authors = [
  { name="David Marcel BAUM", email="contact@davidbaum.org" },
]
description = "Graphical interface for several biosensors including Neuri created by Helment"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Helment/NeuriGUI"
"Bug Tracker" = "https://github.com/Helment/NeuriGUI/issues"
